source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
use_frameworks!

target 'IoTSampleSwift' do
  $awsVersion = '~> 2.12.0'
  pod 'AWSMobileClient', $awsVersion
  pod 'AWSIoT', $awsVersion
end

# add the Firebase pod for Google Analytics
pod 'Firebase/Analytics'
# add pods for any other desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods
